<main id="comment" class="container py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Comment</h2>

    <form action="index.php?route=check-comment&post=<?php echo $_GET['post'] ?>" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?php echo $_SESSION['csrf_token'] ?>" />
        <fieldset class="my-1">
            <label for="comment" class="form-label">
                Comment
            </label>
            <input type="text" name="comment" id="comment" value="" class="form-control"/>
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary">Add</button>
        </fieldset>
    </form>
</main>