<main id="home" class="py-5 px-3">
    <h1 class="mb-5"><?= $this->translator->translate("site_title") ?></h1>

    <h2 class="mt-5"><?= $this->translator->translate("home_title_latest_posts") ?></h2>
    <?php
        echo _("Passez une bonne journée");
    ?>
    <ul class="row mt-5">
        <?php
            foreach($data['posts'] as $val) {
                ?>
                <li class="col-4 my-2">
                    <article class="card">
                        <header class="card-body">
                            <h3 class="h5 card-title"><?php echo $val->getTitle() ?></h3>
                            <h4 class="h6 card-subtitle mb-2 text-body-secondary"><?php echo $val->getCategory()->getTitle() ?></h4>
                        </header>
                        <section class="card-body">
                            <p class="card-text"><?php echo $val->getExcerpt() ?></p>
                            <a href="index.php?route=post&post_id=<?php echo $val->getId() ?>" class="btn btn-primary"><?= $this->translator->translate("post_link_button") ?></a>
                        </section>
                    </article>
                </li>
                <?php
            }
        ?>
    </ul>
</main>