<main id="register" class="container py-5 px-3">
    <h1 class="mb-5"><?= $this->translator->translate("site_title") ?></h1>

    <h2 class="mt-5"><?= $this->translator->translate("register_title") ?></h2>

    <form action="index.php?route=check-register" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?php echo $_SESSION['csrf_token'] ?>" />
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("register_username_label") ?>
            </label>
            <input type="text" name="username" value="" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("register_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("register_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                <?= $this->translator->translate("register_confirm_password_label") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password"  class="form-control"/>
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("register_submit_button") ?></button>
        </fieldset>
    </form>
    <p>
    <?= $this->translator->translate("register_login_text") ?> <a href="index.php?route=login"><?= $this->translator->translate("register_link_text") ?></a>
    </p>
</main>