<main id="register" class="container py-5 px-3">
    <h1 class="mb-5">Blog sécurisé</h1>

    <h2 class="mt-5">Inscription</h2>

    <form action="index.php?route=check-register" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?php echo $_SESSION['csrf_token'] ?>" />
        <fieldset class="my-1">
            <label for="username" class="form-label">Choisissez un nom d'utilisateur</label>
            <input type="text" name="username" value="" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">Entrer votre Email</label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">Choisissez un mot de passe</label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">Confirmer votre mot de passe</label>
            <input type="password" name="confirm-password" id="confirm-password"  class="form-control"/>
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary">Inscription</button>
        </fieldset>
    </form>
    <p>
        Avez vous déjà un compte ?<a href="index.php?route=login">Connectez-vous ici</a>
    </p>
</main>